# Generated by Django 4.1.2 on 2022-10-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolunteerMatching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abandoneddog',
            name='gender',
            field=models.CharField(choices=[('male', '수컷'), ('female', '암컷')], max_length=8),
        ),
    ]
